---

- apt: update_cache=yes

- lineinfile: dest="/etc/profile.d/set_lc_all.sh"
              line='export LC_ALL="en_US.UTF-8"'
              create=yes
              state=present

- apt: pkg={{ item }}
       state=installed
  with_items:
    - postgresql-9.3
    - postgresql-client-9.3
    - postgresql-server-dev-9.3
    - python-dev
    - python-psycopg2
  notify:
    - restart postgres
