---

- apt: update_cache=yes
       cache_valid_time=3600

- apt: pkg={{ item }}
       state=installed
  with_items:
    - language-pack-en
    - apache2
    - libapache2-mod-wsgi

- service: name=apache2
           state=restarted


- file: path=/var/log/segue/
        owner=www-data
        mode=0777
        state=directory

- file: path=/var/log/segue/segue.log
        owner=www-data
        mode=0777
        state=touch

- template: src=handler.wsgi.j2
            dest={{ app_path }}/handler.wsgi
            owner=www-data
            mode=0755
  tags: config

- template: src=apache.conf.j2
            dest=/etc/apache2/conf-enabled/segue.conf
  tags: config
  notify: restart apache

- template: src=settings.py.j2 dest={{ app_path }}/segue/settings.py
            owner=www-data
            mode=0755
  tags: config
  notify:
    - restart segue
